name: Build KISS Radio Firmwares

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'kiss-*'

jobs:
  build-kiss-firmwares:
    uses: ./.github/workflows/firmware-builder.yml
    with:
      firmware_type: 'kiss'
      release_title_prefix: 'KISS Radio Firmware'
